# Generated by Django 4.2.7 on 2023-11-18 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact_form_submission",
            old_name="form_purpose",
            new_name="services",
        ),
        migrations.RemoveField(
            model_name="contact_form_submission",
            name="free_quote",
        ),
        migrations.RemoveField(
            model_name="contact_form_submission",
            name="user_type",
        ),
    ]
